# Stage 1: Build the app
FROM node:18 

WORKDIR /usr/src

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .
# RUN npm run build

# Stage 2: Serve with nginx

# Copy build files to nginx
# COPY --from=build /usr/src/build /usr/share/nginx/html

# Copy custom nginx config (optional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8000

RUN npm run test

CMD ["npm", "run", "start"]
