services:
  backend:
    build: ./backend
    container_name: customer-health-backend
    ports:
      - "8000:8000"
    restart: always
    # volumes:
    #   - ./backend:/usr/src        # 👈 mounts local code into container
    #   # - /usr/node_modules     # 👈 keeps node_modules inside container
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /usr
          ignore:
            - node_modules/

        - action: rebuild
          path: package.json

    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=customer_health
      - PORT=8000
    depends_on:
      # - seeder
      - db

  frontend:
    build: ./frontend
    container_name: customer-health-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - seeder
      - backend
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /usr
          ignore:
            - node_modules/

        - action: rebuild
          path: package.json
    # volumes:
    #   - ./frontend:/usr/src

  db:
    image: postgres:15
    container_name: customer-health-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_health
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # seeder:
  #   build: ./backend
  #   command: node /usr/src/generate_data.js
  #   volumes:
  #     - ./backend:/usr/src
  #   depends_on:
  #     - db

  seeder:
    build: ./backend
    command: sh -c "npm install && npx ts-node ./src/generateData.ts"
    # volumes:
    #   - ./backend:/usr/src
    depends_on:
      - db
      - backend
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=customer_health

volumes:
  db-data:
