# Use official Node.js image
FROM node:18

# Create app directory
WORKDIR /usr/src

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 8000

# Run app
# RUN npm run test
CMD ["npm", "run", "start"]
